spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/product_catalog_service
    username: myapp
    password: a123456a
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true

server.port: 8081

## Enable shutdown endpoint
management:
  endpoints.web.exposure.include: "*"
  endpoint.shutdown.enabled: true

endpoints.shutdown.enabled: true